name: py_sc_analysis_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - jupyter
  - ipykernel
  - pandas=2.0.3
  - numpy=1.23.1
  - scanpy=1.9.5
  - matplotlib=3.7.3
  - tqdm=4.66.1
  - seaborn=0.13.0
  - networkx=3.1
  - adjusttext=1.3.0
  - dask=2023.5.0
  - distributed=2023.5.0
  - numba=0.58.1
  - pip
  - pip:
      - loompy==3.0.7
      - arboreto==0.1.6
      - pyscenic==0.12.1
      - multiprocessing_on_dill==3.5.0a4
